#!/bin/bash

# Google OAuth Quick Setup for Herit
set -e

echo "🔐 Google OAuth Setup for Herit"
echo "================================"
echo ""
echo "Generated SESSION_SECRET for production:"
echo "1lrv3vkIcSBYW9aUlZiZ7TdSLYFIiHIdbxx6nneiYQZOgf/1idcVU6rUtVynP5f8"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 STEP 1: Create Google OAuth Credentials"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://console.cloud.google.com/"
echo "2. Select or create a project (e.g., 'Herit')"
echo "3. Navigate to: APIs & Services → Credentials"
echo "4. Click: Create Credentials → OAuth 2.0 Client ID"
echo "5. Application type: Web application"
echo "6. Name: 'Herit Web App'"
echo ""
echo "7. Add these Authorized redirect URIs:"
echo "   ✓ http://localhost:3000/api/auth/google/callback"
echo "   ✓ http://localhost:3001/api/auth/google/callback"
echo "   ✓ https://herit-claude.vercel.app/api/auth/google/callback"
echo "   ✓ https://herit.vercel.app/api/auth/google/callback"
echo ""
echo "8. Click 'Create' and copy your credentials"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 STEP 2: Add to Vercel (Production)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run these commands with your actual values:"
echo ""
echo "vercel env add GOOGLE_CLIENT_ID production"
echo "# Paste your Client ID (ends with .apps.googleusercontent.com)"
echo ""
echo "vercel env add GOOGLE_CLIENT_SECRET production"
echo "# Paste your Client Secret"
echo ""
echo "vercel env add SESSION_SECRET production"
echo "# Paste: 1lrv3vkIcSBYW9aUlZiZ7TdSLYFIiHIdbxx6nneiYQZOgf/1idcVU6rUtVynP5f8"
echo ""
echo "vercel env add GOOGLE_REDIRECT_URI production"
echo "# Paste: https://herit-claude.vercel.app/api/auth/google/callback"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 STEP 3: Update Local Development (.env.local)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Add these to your .env.local file:"
echo ""
echo 'GOOGLE_CLIENT_ID="YOUR_CLIENT_ID.apps.googleusercontent.com"'
echo 'GOOGLE_CLIENT_SECRET="YOUR_CLIENT_SECRET"'
echo 'SESSION_SECRET="1lrv3vkIcSBYW9aUlZiZ7TdSLYFIiHIdbxx6nneiYQZOgf/1idcVU6rUtVynP5f8"'
echo 'GOOGLE_REDIRECT_URI="http://localhost:3000/api/auth/google/callback"'
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 STEP 4: Deploy and Test"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Deploy to Vercel: git push origin main"
echo "2. Test locally: npm run dev"
echo "3. Visit: http://localhost:3000/login"
echo "4. Click 'Continue with Google'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"